# Generated by Django 4.2.7 on 2023-11-02 18:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('text_en', ckeditor.fields.RichTextField(null=True)),
                ('text_pl', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name': 'Privacy policy',
            },
        ),
    ]
