# Generated by Django 4.2.7 on 2023-11-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='game_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
