# Generated by Django 4.2.5 on 2023-09-12 13:13

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30, null=True)),
                ('name_pl', models.CharField(max_length=30, null=True)),
                ('logo', models.ImageField(blank=True, default='./game_default.png', upload_to=games.models.path_logo)),
                ('description', models.TextField(max_length=200)),
                ('description_en', models.TextField(max_length=200, null=True)),
                ('description_pl', models.TextField(max_length=200, null=True)),
                ('apple_store', models.URLField(blank=True)),
                ('google_store', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-created'],
            },
        ),
    ]
